Repository varunKT001/tomper-wear-ecommerce, pull requests merged in 2022-03, with the labels that each got.

#7 Change spelling 'react' -> 'reach'
  src/pages/AboutPage/index.js
Labels: GSSoC22, Level1

#16 Search bar bug
  package-lock.json
  package.json
  src/reducers/filter_reducer.js
Labels: GSSoC22, Level1

#23 Confirm Password field addded in registration page
  src/pages/RegisterPage/index.js
Labels: GSSoC22, Level1

#32 Footer css
  src/components/Footer/styles.js
  src/utils/constants.js
Labels: GSSoC22, Level1

#36 Loading spinner when button is disabled
  src/components/Button/LoadingIcon.js
  src/components/Button/index.js
  src/components/Contact/index.js
  src/components/ReviewModal/index.js
  src/pages/ForgotPasswordPage/index.js
  src/pages/LoginPage/index.js
  src/pages/ProfilePage/index.js
  src/pages/RegisterPage/index.js
Labels: GSSoC22, Level1

#38 Show/hide password feature added
  package-lock.json
  src/pages/LoginPage/index.js
  src/pages/LoginPage/styles.js
  src/pages/RegisterPage/index.js
  src/pages/RegisterPage/styles.js
Labels: enhancement, level2

#42 Lower Limit added to Price Filter
  src/reducers/filter_reducer.js
Labels: GSSoC22, Level1

#44 Existing password check added before changing password
  src/context/user_context.js
  src/pages/ProfilePage/index.js
Labels: GSSoC22, Level2
